# Umbrales de Cobertura por Módulo - edugo-shared
# Última actualización: 2025-11-23
# Actualizado por: Validación y limpieza de tests unitarios

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FORMATO
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# nombre_modulo:
#   threshold: <número>      # Umbral mínimo (%)
#   current: <número>        # Cobertura actual (%)
#   target: <número>         # Objetivo a 3 meses (%)
#   status: <texto>          # Estado actual
#   priority: <texto>        # Prioridad de mejora
#   notes: <texto>           # Notas adicionales

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÓDULOS CORE (Alta Prioridad - Seguridad y Config)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

auth:
  threshold: 80
  current: 85.0
  target: 90
  status: "✅ Cumple"
  priority: "Mantener"
  notes: "Módulo crítico de seguridad. Mantener >80%, objetivo 90%"
  actions:
    - "Agregar tests para casos de ValidateToken no cubiertos"
    - "Tests para casos edge de ExtractUserID y ExtractRole"

config:
  threshold: 75
  current: 82.9
  target: 85
  status: "✅ Cumple"
  priority: "Mantener"
  notes: "Configuración crítica del sistema. Mantener >75%"
  actions:
    - "Mantener cobertura actual"
    - "Agregar tests para validaciones complejas"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÓDULOS DE INFRAESTRUCTURA (Alta Prioridad)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

logger:
  threshold: 90
  current: 95.8
  target: 100
  status: "✅ Excelente"
  priority: "Mantener"
  notes: "Logging crítico. Solo falta Fatal (0%) que es difícil de testear"
  actions:
    - "Considerar test de Fatal con subprocess"
    - "Mantener 100% en funciones testeables"

lifecycle:
  threshold: 85
  current: 91.8
  target: 95
  status: "✅ Excelente"
  priority: "Mantener"
  notes: "Gestión de recursos y cleanup. Mantener >85%"
  actions:
    - "Agregar tests de edge cases en Startup y Cleanup"

bootstrap:
  threshold: 40
  current: 40.0
  target: 60
  status: "✅ Mejorado en Sprint 4"
  priority: "Media"
  notes: "Mejorado de 35.7% a 40% (+4.3 puntos). Tests de factories completados"
  actions:
    - "✅ Sprint 3: Tests de cleanup lifecycle completados"
    - "✅ Sprint 3: Tests de extract config completados"
    - "✅ Sprint 4: Tests de logger factory con múltiples entornos"
    - "✅ Sprint 4: Tests de buildDSN para PostgreSQL"
    - "Futuro: Tests de factories con containers (CreateConnection, etc)"
    - "Objetivo: 40% → 60%"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÓDULOS DE BASE DE DATOS (Media Prioridad)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

database/postgres:
  threshold: 5
  current: 5.9
  target: 58
  status: "⚠️ Cobertura baja - Requiere mocks (sqlmock)"
  priority: "Alta"
  notes: "Tests unitarios básicos agregados (constantes, validación config). config.go excluido de métrica (solo struct sin lógica). Para alcanzar meta 58% se requiere sqlmock para connection.go y transaction.go"
  exclude_files:
    - "config.go" # Solo struct Config y DefaultConfig() - sin lógica de negocio
  coverage_breakdown:
    - "DefaultConfig(): 100% ✅ (testeado)"
    - "Close(): 66.7% ✅ (nil case testeado)"
    - "Connect(): 0% ❌ (requiere sqlmock)"
    - "HealthCheck(): 0% ❌ (requiere sqlmock)"
    - "GetStats(): 0% ❌ (requiere sqlmock)"
    - "WithTransaction(): 0% ❌ (requiere sqlmock)"
    - "WithTransactionIsolation(): 0% ❌ (requiere sqlmock)"
  actions:
    - "✅ Tests de constantes agregados (previenen regresiones)"
    - "✅ Tests de validación de Config agregados"
    - "Futuro: Implementar tests con sqlmock para funciones de conexión"
    - "Futuro: Tests de transacciones con sqlmock"
    - "Objetivo: 5.9% → 58% (requiere ~15h con sqlmock)"

database/mongodb:
  threshold: 10
  current: 13.6
  target: 80
  status: "⚠️ Cobertura baja - Requiere mocks (mongo driver)"
  priority: "Alta"
  notes: "Tests unitarios básicos agregados (+9.1% desde 4.5%). config.go excluido de métrica (solo struct sin lógica). Para alcanzar meta 80% se requiere mocks del mongo driver"
  exclude_files:
    - "config.go" # Solo struct Config y DefaultConfig() - sin lógica de negocio
  coverage_breakdown:
    - "DefaultConfig(): 100% ✅ (testeado)"
    - "Close(): 40% ✅ (nil case testeado)"
    - "Connect(): 0% ❌ (requiere mocks de mongo.Client)"
    - "GetDatabase(): 0% ❌ (requiere mocks)"
    - "HealthCheck(): 0% ❌ (requiere mocks)"
  actions:
    - "✅ Tests de constantes agregados (previenen regresiones)"
    - "✅ Tests de validación de Config agregados"
    - "✅ Incremento de cobertura +9.1% (4.5% → 13.6%)"
    - "Futuro: Implementar mocks de mongo.Client para Connect()"
    - "Futuro: Tests de HealthCheck() con mocks"
    - "Objetivo: 13.6% → 80% (requiere ~12h con mocks)"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÓDULOS DE INTEGRACIÓN (Variada Prioridad)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

middleware/gin:
  threshold: 95
  current: 98.5
  target: 100
  status: "✅ Excelente"
  priority: "Mantener"
  notes: "Middleware HTTP crítico. Ya casi perfecto"
  actions:
    - "Cubrir el 1.5% restante"
    - "Mantener cobertura alta"

messaging/rabbit:
  threshold: 30
  current: 30.0
  target: 50
  status: "✅ Mejorado en Sprint 4"
  priority: "Media"
  notes: "Mejorado de 14.4% a 30% (+15.6 puntos, +108% mejora). Tests de integración completados"
  actions:
    - "✅ Sprint 2: Agregados tests de config, DLQ helpers"
    - "✅ Sprint 4: Tests de Connection con containers (~24 tests)"
    - "✅ Sprint 4: Tests de Consumer con containers (~20 tests)"
    - "✅ Sprint 4: Tests de Publisher con containers (~21 tests)"
    - "Futuro: Tests de DLQ consumer integration"
    - "Objetivo: 30% → 50%"
  estimated_effort: "2-3 horas para llegar a 50%"

testing:
  threshold: 20
  current: 21.0
  target: 55
  status: "✅ Incremento mínimo - Requiere más tests unitarios"
  priority: "Media"
  notes: "Tests unitarios de helpers agregados (+1%). Tests de integración requieren INTEGRATION_TESTS=true. Para alcanzar meta 55% se requieren tests unitarios de options.go, config.go y manager.go sin containers"
  exclude_files:
    - "*_integration_test.go" # Tests de integración requieren containers
  coverage_breakdown:
    containers:
      - "helpers.go: Parcialmente cubierto con helpers_unit_test.go ✅"
      - "options.go: 0% ❌ (requiere tests unitarios)"
      - "config.go: 0% ❌ (requiere tests unitarios)"
      - "manager.go: 0% ❌ (requiere mocks, muy acoplado a containers)"
      - "postgres.go, mongodb.go, rabbitmq.go: Requieren containers (tests de integración)"
  actions:
    - "✅ helpers_unit_test.go agregado (9 tests, edge cases de paths)"
    - "✅ Incremento de cobertura +1% (20% → 21%)"
    - "Futuro: Agregar options_unit_test.go para configuración de containers"
    - "Futuro: Agregar config_unit_test.go para builder pattern"
    - "Futuro: Considerar refactor de manager.go para facilitar tests unitarios"
    - "Objetivo: 21% → 55% (requiere ~8-10h de trabajo)"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÓDULOS CON PROBLEMAS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

common:
  threshold: 0
  current: "95% estimado (con issue covdata)"
  target: 70
  status: "✅ Documentado (issue técnico de Go 1.25)"
  priority: "Baja"
  notes: "Issue de covdata documentado. Tests pasan (100% validator, 97.8% errors, 94.6% types). Excluir de validación automática"
  actions:
    - "✅ Issue documentado en COMMON-COVDATA-ISSUE.md"
    - "Futuro: Revisar en Go 1.25.5+ si persiste"
    - "Futuro: Considerar split de common en módulos separados"
  estimated_effort: "Monitorear en futuras versiones de Go"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CONFIGURACIÓN GLOBAL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

global:
  default_threshold: 50
  minimum_acceptable: 30
  excellent_threshold: 80
  target_global: 65
  current_global: "~60% (estimado, excluyendo common)"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ESTRATEGIA DE MEJORA POR FASES
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

improvement_plan:
  sprint_2:
    - "Resolver error en common (1-2h)"
    - "messaging/rabbit: 2.9% → 15% (3-4h)"

  sprint_3:
    - "bootstrap: 29.5% → 40% (2-3h)"
    - "database/postgres: 58.8% → 60% (1h)"
    - "database/mongodb: 54.5% → 55% (1h)"

  sprint_4:
    - "messaging/rabbit: 15% → 30% (2-3h)"
    - "bootstrap: 40% → 60% (2h)"

  sprint_5:
    - "Incrementar umbrales de módulos que cumplen"
    - "messaging/rabbit: 30% → 50%"
    - "Review general y ajustes"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MÉTRICAS DE SEGUIMIENTO
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

metrics:
  modules_meeting_threshold:
    current: 8
    target: 12

  modules_excellent:
    current: 4 # auth, logger, lifecycle, middleware/gin
    target: 7

  modules_critical:
    current: 1 # messaging/rabbit
    target: 0

  modules_with_errors:
    current: 1 # common
    target: 0
