# Configuración MÍNIMA para golangci-lint v2.x
# https://golangci-lint.run/usage/configuration/

# Versión de configuración (DEBE ser string en v2.x)
version: "2"

run:
  timeout: 5m

# Linters habilitados (compatible v2.x)
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
