# Configuración MÍNIMA para golangci-lint v2.x
# https://golangci-lint.run/usage/configuration/

# Versión de configuración (DEBE ser string en v2.x)
version: "2"

run:
  timeout: 5m

# Linters habilitados (v2.x compatible)
# NOTA: gofmt y goimports ahora son formatters, no linters
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
