# Configuración para golangci-lint
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-use-default: false

linters-settings:
  govet:
    enable-all: true
  
  golint:
    min-confidence: 0.8
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/EduGoGroup/edugo-shared
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  funlen:
    lines: 100
    statements: 50
  
  gocyclo:
    min-complexity: 15
  
  maligned:
    suggest-new: true
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  # depguard disabled for shared library - allows all imports
  # depguard:
  #   list-type: blacklist
  #   packages: []
  
  misspell:
    locale: US
  
  lll:
    line-length: 140
  
  unused:
    check-exported: false
  
  unparam:
    check-exported: false
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive  # replaces golint
    - mnd     # replaces gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - predeclared    # detects shadowing
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused  # replaces deadcode, structcheck, varcheck
    - whitespace
    - copyloopvar    # replaces exportloopref
    # Disable some that are too strict for this shared library
    # - funlen
    # - dogsled
    # - dupl
    # - depguard   # allows all imports for shared library
  
  disable: []
  
  fast: false