# Coverage configuration for edugo-shared
# Excluye archivos/carpetas que no necesitan testing obligatorio

# Threshold configuration
coverage:
  # Coverage goal for the project
  threshold: 80.0
  # Minimum coverage required to pass
  min-coverage: 70.0

# Files and directories to exclude from coverage calculation
exclude:
  # Configuration files - solo getters de env vars
  - "pkg/config/**"
  
  # Error definitions - solo constructores
  - "pkg/errors/errors.go"
  
  # Type definitions and enums - mayormente constantes
  - "pkg/types/enum/**"
  
  # Generated files
  - "**/*_gen.go"
  - "**/*_generated.go"
  
  # Test files (obvio)
  - "**/*_test.go"
  
  # Vendor and dependencies
  - "vendor/**"
  - "third_party/**"

# Files that MUST be tested (critical business logic)
require-coverage:
  - "pkg/auth/**"
  - "pkg/database/**"
  - "pkg/logger/**"
  - "pkg/messaging/**" 
  - "pkg/validator/**"

# Files that are optional but recommended to test
optional-coverage:
  - "pkg/types/uuid.go"  # Has some logic worth testing